Repository thoth-station/messaging, pull requests merged in 2019-10, with the labels that each got.

#3 added create_topic, publish_to_topic
  CHANGELOG.md
  thoth/messaging/__init__.py
  thoth/messaging/package_releases.py
  thoth/messaging/publish.py
Labels: size/M

#5 added a release pipeline job to push to pypi
  .zuul.yaml
Labels: approved, size/S

#23 Automatic update of dependency thoth-common from 0.9.10 to 0.9.12
  Pipfile.lock
Labels: bot

#24 Automatic update of dependency faust from 1.7.4 to 1.8.0
  Pipfile.lock
Labels: bot

#25 Automatic update of dependency pytest from 5.1.3 to 5.2.1
  Pipfile.lock
Labels: bot

#26 Automatic update of dependency pytest-cov from 2.7.1 to 2.8.1 [WIP]
  Pipfile.lock
Labels: bot, do-not-merge/work-in-progress

#28 Release of version 0.2.1
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: bot, size/S

#30 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#34 Automatic update of dependency faust from 1.8.0 to 1.8.1
  Pipfile.lock
Labels: bot

#36 Automatic update of dependency pytest from 5.2.1 to 5.2.2
  Pipfile.lock
Labels: bot

#37 Automatic update of dependency black from 19.3b0 to 19.10b0
  Pipfile.lock
Labels: bot

#38 Automatic update of dependency faust from 1.8.1 to 1.9.0
  Pipfile.lock
Labels: bot
