Repository thoth-station/messaging, pull requests merged in 2020-08, with the labels that each got.

#190 wait for topic to be declared before trying to publish
  cli.py
Labels: approved, size/XS

#195 extra set of parenthesis removed
  cli.py
Labels: approved, size/XS

#191 be strict about message contents
  thoth/messaging/message_factory.py
Labels: approved, size/S

#197 Release of version 0.6.3
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/S

#198 allow ci to release the project to pypi
  .aicoe-ci.yaml
Labels: approved, size/XS

#199 Add unrevsolved class
  thoth/messaging/__init__.py
  thoth/messaging/unrevsolved_package.py
Labels: approved, size/M

#200 add dev documentation for thoth-messaging
  README.rst
  docker-compose.yaml
Labels: approved, size/M

#202 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#204 Automatic update of dependency pytest-cov from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot, size/M

#205 Release of version 0.6.4
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#206 Automatic update of dependency pytest-cov from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot, size/M

#213 allow for batch sending of messages
  Pipfile
  Pipfile.lock
  cli.py
Labels: approved, size/L

#217 prepend deployment_name if it exists
  cli.py
  thoth/messaging/message_base.py
Labels: approved, size/XS

#219 Release of version 0.6.6
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#221 Correct typo in import
  cli.py
Labels: approved, size/XS

#223 Release of version 0.6.7
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#226 Automatic update of dependency thoth-common from 0.16.1 to 0.17.0
  Pipfile.lock
Labels: approved, bot, size/L

#228 Provide service version
  cli.py
Labels: approved, size/XS

#224 add default message contents for traceability
  cli.py
  thoth/messaging/__init__.py
  thoth/messaging/advise_justification.py
  thoth/messaging/adviser_re_run.py
  thoth/messaging/hash_mismatch.py
  thoth/messaging/message_base.py
  thoth/messaging/message_factory.py
  thoth/messaging/missing_package.py
  thoth/messaging/missing_version.py
  thoth/messaging/package_releases.py
  thoth/messaging/solved_package.py
  thoth/messaging/unresolved_package.py
  thoth/messaging/unrevsolved_package.py
Labels: approved, size/M

#233 Release of version 0.7.0
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/S
