Repository thoth-station/messaging, pull requests merged in 2020-03, with the labels that each got.

#95 Automatic update of dependency thoth-common from 0.10.9 to 0.10.11
  Pipfile.lock
Labels: bot, size/M

#97 Automatic update of dependency pytest from 5.3.5 to 5.4.0
  Pipfile.lock
Labels: bot, size/S

#98 Automatic update of dependency pytest from 5.4.0 to 5.4.1
  Pipfile.lock
Labels: bot, size/XS

#99 Automatic update of dependency thoth-common from 0.10.11 to 0.10.12
  Pipfile.lock
Labels: bot, size/L

#101 Automatic update of dependency thoth-common from 0.10.12 to 0.12.0
  Pipfile.lock
Labels: bot, size/M

#102 Automatic update of dependency thoth-common from 0.12.0 to 0.12.1
  Pipfile.lock
Labels: bot, size/S

#103 Automatic update of dependency thoth-common from 0.12.1 to 0.12.2
  Pipfile.lock
Labels: bot, size/M

#104 Automatic update of dependency thoth-common from 0.12.2 to 0.12.3
  Pipfile.lock
Labels: bot, size/XS

#105 Automatic update of dependency thoth-common from 0.12.3 to 0.12.4
  Pipfile.lock
Labels: bot, size/S

#106 Remove prereleases
  Pipfile
  Pipfile.lock
Labels: approved

#108 Adjust requirements not to lock sub-dependencies
  requirements-test.txt
  requirements.txt
Labels: approved, size/L

#110 Release of version 0.3.3
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: bot, size/M

#112 Remove index configuration from requirements.txt
  requirements.txt
Labels: approved

#115 Release of version 0.3.4
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: bot
