Repository thoth-station/messaging, pull requests merged in 2020-09, with the labels that each got.

#234 Automatic update of dependency thoth-common from 0.17.0 to 0.17.2
  Pipfile.lock
Labels: approved, bot

#238 Automatic update of dependency thoth-common from 0.17.2 to 0.18.0
  Pipfile.lock
Labels: approved, bot, size/M

#237 Adjust docstrings
  thoth/messaging/advise_justification.py
  thoth/messaging/adviser_re_run.py
  thoth/messaging/hash_mismatch.py
  thoth/messaging/missing_version.py
  thoth/messaging/package_releases.py
  thoth/messaging/solved_package.py
  thoth/messaging/unresolved_package.py
  thoth/messaging/unrevsolved_package.py
Labels: approved, size/S

#239 Automatic update of dependency thoth-common from 0.18.0 to 0.18.1
  Pipfile.lock
Labels: approved, bot, size/XS

#240 Adjust links in README
  README.rst
Labels: approved, size/XS

#241 Automatic update of dependency thoth-common from 0.18.1 to 0.18.3
  Pipfile.lock
Labels: approved, bot, size/M

#242 Automatic update of dependency pytest from 6.0.1 to 6.0.2
  Pipfile.lock
Labels: approved, bot, size/M

#243 Added un analyzed topic
  thoth/messaging/__init__.py
  thoth/messaging/si_unanalyzed_package.py
Labels: approved, size/M

#235 add scheduling messages
  thoth/messaging/__init__.py
  thoth/messaging/adviser_trigger.py
  thoth/messaging/kebechet_trigger.py
  thoth/messaging/package_extract_trigger.py
  thoth/messaging/provenance_checker_trigger.py
  thoth/messaging/qebhwt_trigger.py
Labels: approved, size/L

#246 Release of version 0.7.1
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/S

#248 rename to PackageReleasedMessage
  thoth/messaging/__init__.py
  thoth/messaging/package_releases.py
Labels: approved, size/S

#251 Release of version 0.7.2
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#252 Automatic update of dependency thoth-common from 0.18.3 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/S

#255 enable messaging packages to be imported
  thoth/messaging/__init__.py
Labels: approved, size/XS

#257 Release of version 0.7.3
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/S

#258 Adjust logic and improve logging
  cli.py
Labels: approved, size/S

#261 Release of version 0.7.4
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#262 Remove key_type
  thoth/messaging/message_base.py
Labels: approved, size/XS

#264 Release of version 0.7.5
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#265 move init_logging
  cli.py
Labels: approved, size/XS

#267 Release of version 0.7.6
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#269 pass directory to store rocksDB
  thoth/messaging/message_base.py
Labels: approved, size/S

#268 add versions to all messages
  thoth/messaging/advise_justification.py
  thoth/messaging/adviser_re_run.py
  thoth/messaging/adviser_trigger.py
  thoth/messaging/hash_mismatch.py
  thoth/messaging/kebechet_trigger.py
  thoth/messaging/message_base.py
  thoth/messaging/message_factory.py
  thoth/messaging/missing_package.py
  thoth/messaging/missing_version.py
  thoth/messaging/package_extract_trigger.py
  thoth/messaging/package_releases.py
  thoth/messaging/provenance_checker_trigger.py
  thoth/messaging/qebhwt_trigger.py
  thoth/messaging/si_unanalyzed_package.py
  thoth/messaging/solved_package.py
  thoth/messaging/unresolved_package.py
  thoth/messaging/unrevsolved_package.py
Labels: approved, size/M

#270 add message for completed inspections
  thoth/messaging/inspection_complete.py
Labels: approved, size/M

#271 add new message to update flag
  thoth/messaging/message_factory.py
  thoth/messaging/update_is_downloadable_ppv.py
Labels: approved, size/M

#273 Automatic update of dependency thoth-common from 0.19.0 to 0.20.0
  Pipfile.lock
Labels: approved, bot, size/L

#274 Automatic update of dependency thoth-common from 0.19.0 to 0.20.0
  Pipfile.lock
Labels: approved, bot, size/L

#275 Automatic update of dependency pytest from 6.0.2 to 6.1.0
  Pipfile.lock
Labels: approved, bot, size/L

#277 Release of version 0.7.7
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/S

#278 Change message
  thoth/messaging/is_package_si_analyzable.py
Labels: approved, size/S

#280 Release of version 0.7.8
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot

#281 change name of message
  thoth/messaging/update_provides_src_distro.py
Labels: approved, size/S

#283 Release of version 0.7.9
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS
