Repository thoth-station/messaging, pull requests merged in 2020-07, with the labels that each got.

#144 Add missing import to use the class
  thoth/messaging/__init__.py
Labels: approved, size/XS

#146 Automatic update of dependency thoth-common from 0.13.8 to 0.14.1
  Pipfile.lock
Labels: approved, bot

#147 Automatic update of dependency thoth-common from 0.13.8 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/L

#148 Automatic update of dependency pytest-timeout from 1.3.4 to 1.4.1
  Pipfile.lock
Labels: approved, bot, size/L

#150 Automatic update of dependency pytest-cov from 2.9.0 to 2.10.0
  Pipfile.lock
Labels: approved, bot, size/L

#152 Automatic update of dependency pylint from 2.5.2 to 2.5.3
  Pipfile.lock
Labels: approved, bot, size/L

#154 Automatic update of dependency pylint from 2.5.2 to 2.5.3
  Pipfile.lock
Labels: approved, bot, size/XS

#156 Add maintainer
  .thoth.yaml
Labels: approved, size/XS

#159 Release of version 0.3.7
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/S

#162 Adjust message specs
  thoth/messaging/unresolved_package.py
Labels: approved, size/XS

#160 Modify class not be initialized during import
  Pipfile
  Pipfile.lock
  requirements.txt
  thoth/messaging/advise_justification.py
  thoth/messaging/hash_mismatch.py
  thoth/messaging/message_base.py
  thoth/messaging/message_factory.py
  thoth/messaging/missing_package.py
  thoth/messaging/missing_version.py
  thoth/messaging/package_releases.py
  thoth/messaging/unresolved_package.py
Labels: approved, size/L

#164 Automatic update of dependency pytest-timeout from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: approved, bot, size/XS

#166 Release of version 0.4.0
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot

#168 Release of version 0.5.0
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/L

#169 Release of version 0.6.0
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/L

#171 revert the release of v0.5.0 and v0.6.0
  CHANGELOG.md
Labels: approved, size/XL

#170 Add cli for sending a single message to a topic
  cli.py
  thoth/messaging/__init__.py
  thoth/messaging/message_base.py
  thoth/messaging/message_factory.py
Labels: approved, size/L

#173 Release of version 0.5.0
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#174 remove create topic, topic is created during __init__
  thoth/messaging/message_base.py
Labels: approved, size/S

#177 Release of version 0.6.0
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#179 Add paramter to AdviseJustificaitonMessage
  thoth/messaging/advise_justification.py
Labels: approved, size/XS

#178 Add solved message
  thoth/messaging/solved_package.py
Labels: approved, size/M

#181 Add missing import
  thoth/messaging/__init__.py
Labels: approved, size/XS

#175 Code quality/add precommit
  .github/CODEOWNERS
  .pre-commit-config.yaml
  README.rst
  cli.py
  pyproject.toml
  setup.py
  thoth/messaging/__init__.py
  thoth/messaging/advise_justification.py
  thoth/messaging/hash_mismatch.py
  thoth/messaging/message_base.py
  thoth/messaging/message_factory.py
  thoth/messaging/missing_package.py
  thoth/messaging/missing_version.py
  thoth/messaging/package_releases.py
  thoth/messaging/solved_package.py
  thoth/messaging/unresolved_package.py
Labels: approved, size/L

#180 Adjust README
  README.rst
Labels: approved, size/XS

#182 Add missing PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/S

#184 Release of version 0.6.1
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/S

#185 Deployment/add script
  .github/PULL_REQUEST_TEMPLATE.md
  README.rst
  app.sh
Labels: approved, size/XS

#187 Release of version 0.6.2
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#188 include aicoe-ci configuration file
  .aicoe-ci.yaml
Labels: approved, size/S

#192 Automatic update of dependency pytest from 5.4.3 to 6.0.0
  Pipfile.lock
Labels: approved, bot, size/L

#193 remove coala-bears from requirements-test.txt
  requirements-test.txt
  tests/placeholder_test.py
Labels: approved, size/XS

#194 Automatic update of dependency pytest from 6.0.0 to 6.0.1
  Pipfile.lock
Labels: approved, bot, size/XS

#189 Included typing in message factory
  .env.template
  .gitignore
  thoth/messaging/message_factory.py
Labels: approved, size/XS
