Repository thoth-station/messaging, pull requests merged in 2020-02, with the labels that each got.

#77 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#79 Release of version 0.3.0
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: bot, size/M

#80 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/S

#81 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#82 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/M

#83 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#84 Automatic update of dependency faust from 1.10.1 to 1.10.2
  Pipfile.lock
Labels: bot, size/M

#85 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/S

#87 Release of version 0.3.1
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: bot, size/S

#89 Release of version 0.3.2
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: bot, size/XS

#90 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/S

#91 Automatic update of dependency faust from 1.10.2 to 1.10.3
  Pipfile.lock
Labels: bot, size/S

#92 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/L

#93 Automatic update of dependency faust from 1.10.3 to 1.10.4
  Pipfile.lock
Labels: bot, size/M

#94 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/S
