Repository thoth-station/messaging, pull requests merged in 2020-05, with the labels that each got.

#129 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/S

#130 Add unresolved package message
  Pipfile
  Pipfile.lock
  thoth/messaging/unresolved_package.py
Labels: approved, size/XL

#132 Release of version 0.3.5
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: bot, size/S

#133 Automatic update of dependency pytest from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/S

#116 Message factory
  README.rst
  thoth/messaging/__init__.py
  thoth/messaging/message_factory.py
Labels: approved, size/M

#134 Use solver and adjust typing
  thoth/messaging/unresolved_package.py
Labels: approved, size/XS

#136 Release of version 0.3.6
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: bot, size/S

#137 Automatic update of dependency thoth-common from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/L

#138 Automatic update of dependency thoth-common from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/S

#139 Automatic update of dependency thoth-common from 0.13.5 to 0.13.6
  Pipfile.lock
Labels: bot, size/XS

#140 Automatic update of dependency pytest-cov from 2.8.1 to 2.9.0
  Pipfile.lock
Labels: bot, size/XS

#141 Automatic update of dependency thoth-common from 0.13.6 to 0.13.7
  Pipfile.lock
Labels: bot, size/XS

#142 Automatic update of dependency thoth-common from 0.13.7 to 0.13.8
  Pipfile.lock
Labels: bot, size/S
