Repository thoth-station/messaging, pull requests merged in 2020-10, with the labels that each got.

#284 Add missing import in init
  thoth/messaging/__init__.py
Labels: approved, size/XS

#286 Release of version 0.7.10
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#290 Add adviser version parameter
  thoth/messaging/__init__.py
  thoth/messaging/advise_justification.py
Labels: approved, size/XS

#292 Automatic update of dependency pytest from 6.1.0 to 6.1.1
  Pipfile.lock
Labels: approved, bot

#294 Release of version 0.7.11
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#295 add option for SASL auth
  thoth/messaging/advise_justification.py
  thoth/messaging/adviser_re_run.py
  thoth/messaging/adviser_trigger.py
  thoth/messaging/hash_mismatch.py
  thoth/messaging/inspection_complete.py
  thoth/messaging/kebechet_trigger.py
  thoth/messaging/message_base.py
  thoth/messaging/message_factory.py
  thoth/messaging/missing_package.py
  thoth/messaging/missing_version.py
  thoth/messaging/package_extract_trigger.py
  thoth/messaging/package_releases.py
  thoth/messaging/provenance_checker_trigger.py
  thoth/messaging/qebhwt_trigger.py
  thoth/messaging/si_unanalyzed_package.py
  thoth/messaging/solved_package.py
  thoth/messaging/unresolved_package.py
  thoth/messaging/unrevsolved_package.py
  thoth/messaging/update_provides_src_distro.py
Labels: approved, size/L

#297 Automatic update of dependency thoth-common from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: approved, bot, size/S

#299 Release of version 0.7.12
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#288 add version to message contents
  thoth/messaging/advise_justification.py
  thoth/messaging/adviser_re_run.py
  thoth/messaging/adviser_trigger.py
  thoth/messaging/hash_mismatch.py
  thoth/messaging/inspection_complete.py
  thoth/messaging/kebechet_trigger.py
  thoth/messaging/message_base.py
  thoth/messaging/missing_package.py
  thoth/messaging/missing_version.py
  thoth/messaging/package_extract_trigger.py
  thoth/messaging/package_releases.py
  thoth/messaging/provenance_checker_trigger.py
  thoth/messaging/qebhwt_trigger.py
  thoth/messaging/si_unanalyzed_package.py
  thoth/messaging/solved_package.py
  thoth/messaging/unresolved_package.py
  thoth/messaging/unrevsolved_package.py
  thoth/messaging/update_provides_src_distro.py
Labels: approved, size/M

#300 Confluent rework
  Pipfile
  Pipfile.lock
  cli.py
  thoth/messaging/admin_client.py
  thoth/messaging/advise_justification.py
  thoth/messaging/adviser_re_run.py
  thoth/messaging/adviser_trigger.py
  thoth/messaging/config.py
  thoth/messaging/consumer.py
  thoth/messaging/hash_mismatch.py
  thoth/messaging/inspection_complete.py
  thoth/messaging/kebechet_run_url.py
  thoth/messaging/kebechet_trigger.py
  thoth/messaging/message_base.py
  thoth/messaging/message_factory.py
  thoth/messaging/missing_package.py
  thoth/messaging/missing_version.py
  thoth/messaging/package_extract_trigger.py
  thoth/messaging/package_releases.py
  thoth/messaging/producer.py
  thoth/messaging/provenance_checker_trigger.py
  thoth/messaging/qebhwt_trigger.py
  thoth/messaging/si_unanalyzed_package.py
  thoth/messaging/solved_package.py
  thoth/messaging/unresolved_package.py
  thoth/messaging/unrevsolved_package.py
  thoth/messaging/update_provides_src_distro.py
Labels: approved, size/XXL

#308 Automatic dependency re-locking
  Pipfile.lock
Labels: approved, bot, size/L

#313 Release of version 0.8.0
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#306 add CVEProvidedMessage
  thoth/messaging/__init__.py
  thoth/messaging/cve_provided.py
Labels: approved, size/M

#314 Updated requirements to use confluent instead of faust
  .env.template
  README.rst
  app.sh
  requirements.txt
  thoth/messaging/message_factory.py
Labels: approved, size/S

#316 Release of version 0.8.1
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS

#317 pass ca location for ssl alg
  .env.template
  README.rst
  thoth/messaging/config.py
  thoth/messaging/producer.py
Labels: approved, size/XS

#320 Release of version 0.8.2
  CHANGELOG.md
  thoth/messaging/__init__.py
Labels: approved, bot, size/XS
