Repository thoth-station/messaging, pull requests merged in 2021-06, with the labels that each got.

#428 add config for ssl keystore and password
  thoth/messaging/config.py
Labels: approved, size/XS

#430 all message senders pass index url explicitly
  thoth/messaging/unresolved_package.py
Labels: approved, size/XS

#434 set badges for easy access to content
  README.rst
Labels: approved, size/S

#437 fix issue1445 on user-api
  thoth/messaging/adviser_trigger.py
  thoth/messaging/provenance_checker_trigger.py
Labels: approved, lgtm, size/XS

#440 Deprecate qeb-hwt trigger message
  thoth/messaging/__init__.py
  thoth/messaging/qebhwt_trigger.py
Labels: approved, lgtm, size/M
