Repository thoth-station/messaging, pull requests merged in 2021-04, with the labels that each got.

#395 Add Kevin to maintainers
  .thoth.yaml
Labels: approved, size/XS

#373 F/pydantic messages
  Pipfile
  Pipfile.lock
  README.rst
  cli.py
  requirements.txt
  setup.py
  thoth/messaging/__init__.py
  thoth/messaging/admin_client.py
  thoth/messaging/advise_justification.py
  thoth/messaging/adviser_re_run.py
  thoth/messaging/adviser_trigger.py
  thoth/messaging/build_analysis_trigger.py
  thoth/messaging/consumer.py
  thoth/messaging/cve_provided.py
  thoth/messaging/hash_mismatch.py
  thoth/messaging/inspection_complete.py
  thoth/messaging/kebechet_run_url.py
  thoth/messaging/kebechet_trigger.py
  thoth/messaging/message_base.py
  thoth/messaging/message_factory.py
  thoth/messaging/missing_package.py
  thoth/messaging/missing_version.py
  thoth/messaging/package_extract_trigger.py
  thoth/messaging/package_releases.py
  thoth/messaging/producer.py
  thoth/messaging/provenance_checker_trigger.py
  thoth/messaging/py.typed
  thoth/messaging/qebhwt_trigger.py
  thoth/messaging/si_unanalyzed_package.py
  thoth/messaging/solved_package.py
  thoth/messaging/unresolved_package.py
  thoth/messaging/unrevsolved_package.py
  thoth/messaging/update_provides_src_distro.py
Labels: approved, size/XXL

#398 Add bits needed for publishing docs on thoth-station.ninja
  README.rst
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/source/index.rst
Labels: approved, size/L

#404 missing config for typing.Any
  thoth/messaging/kebechet_trigger.py
Labels: approved, lgtm, size/XS

#409 Remove adviser re run message
  thoth/messaging/__init__.py
  thoth/messaging/adviser_re_run.py
Labels: approved, lgtm, size/M

#410 add blurb about naive schemas
  README.rst
Labels: approved, size/XS

#411 use Strict types provided by pydantic
  thoth/messaging/advise_justification.py
  thoth/messaging/adviser_trigger.py
  thoth/messaging/build_analysis_trigger.py
  thoth/messaging/cve_provided.py
  thoth/messaging/hash_mismatch.py
  thoth/messaging/inspection_complete.py
  thoth/messaging/kebechet_run_url.py
  thoth/messaging/kebechet_trigger.py
  thoth/messaging/message_base.py
  thoth/messaging/missing_package.py
  thoth/messaging/missing_version.py
  thoth/messaging/package_extract_trigger.py
  thoth/messaging/package_releases.py
  thoth/messaging/provenance_checker_trigger.py
  thoth/messaging/qebhwt_trigger.py
  thoth/messaging/si_unanalyzed_package.py
  thoth/messaging/solved_package.py
  thoth/messaging/unresolved_package.py
  thoth/messaging/unrevsolved_package.py
  thoth/messaging/update_provides_src_distro.py
Labels: approved, size/L

#408 Readme restructured text code-block fix
  README.rst
Labels: approved, size/XS
