Repository thoth-station/messaging, pull requests merged in 2021-01, with the labels that each got.

#326 Add build analysis trigger message
  thoth/messaging/__init__.py
  thoth/messaging/build_analysis_trigger.py
Labels: approved, size/M

#330 Extend build analysis message
  thoth/messaging/build_analysis_trigger.py
Labels: approved, size/S

#339 inspection_complete missing from __init__.py
  thoth/messaging/__init__.py
Labels: approved, size/XS

#345 change message contents of inspection complete
  .github/PULL_REQUEST_TEMPLATE.md
  thoth/messaging/inspection_complete.py
Labels: approved, size/XS

#346 add function for connection health
  thoth/messaging/admin_client.py
Labels: approved, size/S
