Repository thoth-station/messaging, pull requests merged in 2021-03, with the labels that each got.

#383 add .prow.yaml
  .aicoe-ci.yaml
  .prow.yaml
Labels: size/M

#375 add kebechet meta
  thoth/messaging/adviser_trigger.py
  thoth/messaging/provenance_checker_trigger.py
Labels: approved, size/S

#390 Add authenticated parameter to the advise-triggering message
  thoth/messaging/adviser_trigger.py
Labels: approved, size/XS
